### ISSUE TITLE
Panic when open cab archive

### ISSUE THREAD

**Issue by ikrivosheev** [mdsteele/rust-cab#15]
Hello! I get `panic` when try open cab archive: `thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ikrivosheev/.local/share/cargo/registry/src/rust-mirror.ptsecurity.ru-8e2111e0e0190772/cab-0.3.0/src/internal/cabinet.rs:601:15`

Dropbox link to the file: https://www.dropbox.com/s/uyad749bo9k8pgi/data1.cab?dl=0

**Comment by mdsteele** [comment]
Thanks for the report.  It looks like that CAB file contains two folders, the second of which contains only an empty file, and thus no data blocks.  The `FolderReader::seek()` method was not handling that case well, crashing when trying to seek to the beginning of a folder when the list of data blocks is empty.  Should be simple enough to fix.

**Comment by mdsteele** [comment]
Sure, I've now published this as [v0.4.1](https://crates.io/crates/cab/0.4.1).

**Comment by ikrivosheev** [comment]
@mdsteele thanks a lot!
