### ISSUE TITLE
Please, make a new release

### ISSUE THREAD

**Issue by slonopotamus** [mdsteele/rust-cab#5]
#3 together with https://github.com/burtonageo/cargo-bundle/pull/70 are required to make `cargo-bundle` work on x86_64-pc-windows-gnu. Until there is a `rust-cab` release with #3, `cargo-bundle` would need to depend on git version of `rust-cab`.

**Comment by mdsteele** [comment]
Published as [v0.2.0](https://crates.io/crates/cab/0.2.0).
